name: 'Simple NPM package by FireWork Production Private Ltd.'
description: 'I will console.log() welcome message'
author: 'up1512001'

inputs:
  gh-token:
    description: 'The Github token for authentication'
    required: true

runs:
  using: 'node16'
  main: 'index.js'

branding:
  icon: 'activity'
  color: 'yellow'
